<?php
/**
 * @category   OM
 * @package    OM_Gallery
 * @author     kumar.dhananjay@orangemantra.in
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace OM\Gallery\Block;

use Magento\Framework\View\Element\Template\Context;
use OM\Gallery\Model\GalleryFactory;
/**
 * Gallery List block
 */
class GalleryListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Gallery
     */
    protected $_gallery;
    public function __construct(
        Context $context,
        GalleryFactory $gallery
    ) {
        $this->_gallery = $gallery;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('OM Gallery Module List Page'));
        
        if ($this->getGalleryCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'om.gallery.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getGalleryCollection()
            );
            $this->setChild('pager', $pager);
            $this->getGalleryCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getGalleryCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $gallery = $this->_gallery->create();
        $collection = $gallery->getCollection();
        $collection->addFieldToFilter('status','1');
        //$gallery->setOrder('gallery_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}