<?php
/**
 * @category   OM
 * @package    OM_HomeSlider
 * @author     kumar.dhananjay@orangemantra.in
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace OM\HomeSlider\Controller\Index;

use Magento\Framework\App\Action\Context;
use OM\HomeSlider\Model\HomeSliderFactory;

class Save extends \Magento\Framework\App\Action\Action
{
	/**
     * @var HomeSlider
     */
    protected $_homeslider;

    public function __construct(
		Context $context,
        HomeSliderFactory $homeslider
    ) {
        $this->_homeslider = $homeslider;
        parent::__construct($context);
    }
	public function execute()
    {
        $data = $this->getRequest()->getParams();
    	$homeslider = $this->_homeslider->create();
        $homeslider->setData($data);
        if($homeslider->save()){
            $this->messageManager->addSuccessMessage(__('You saved the data.'));
        }else{
            $this->messageManager->addErrorMessage(__('Data was not saved.'));
        }
        $resultRedirect = $this->resultRedirectFactory->create();
        $resultRedirect->setPath('homeslider/index/index');
        return $resultRedirect;
    }
}
