<?php
/**
 * @category   OM
 * @package    OM_HomeSlider
 * @author     kumar.dhananjay@orangemantra.in
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace OM\HomeSlider\Controller\Index;

use Magento\Framework\App\Action\Context;
use Magento\Framework\Exception\NotFoundException;
use OM\HomeSlider\Block\HomeSliderView;

class View extends \Magento\Framework\App\Action\Action
{
	protected $_homesliderview;

	public function __construct(
        Context $context,
        HomeSliderView $homesliderview
    ) {
        $this->_homesliderview = $homesliderview;
        parent::__construct($context);
    }

	public function execute()
    {
    	if(!$this->_homesliderview->getSingleData()){
    		throw new NotFoundException(__('Parameter is incorrect.'));
    	}
    	
        $this->_view->loadLayout();
        $this->_view->getLayout()->initMessages();
        $this->_view->renderLayout();
    }
}
