<?php
/**
 * @category   OM
 * @package    OM_HomeSlider
 * @author     kumar.dhananjay@orangemantra.in
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace OM\HomeSlider\Block;

use Magento\Framework\View\Element\Template\Context;
use OM\HomeSlider\Model\HomeSliderFactory;
/**
 * HomeSlider List block
 */
class HomeSliderListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var HomeSlider
     */
    protected $_homeslider;
    public function __construct(
        Context $context,
        HomeSliderFactory $homeslider
    ) {
        $this->_homeslider = $homeslider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('OM HomeSlider Module List Page'));
        
        if ($this->getHomeSliderCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'om.homeslider.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getHomeSliderCollection()
            );
            $this->setChild('pager', $pager);
            $this->getHomeSliderCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getHomeSliderCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $homeslider = $this->_homeslider->create();
        $collection = $homeslider->getCollection();
        $collection->addFieldToFilter('status','1');
        //$homeslider->setOrder('homeslider_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}