<?php
/**
 * @category   OM
 * @package    OM_HomeSlider
 * @author     kumar.dhananjay@orangemantra.in
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace OM\HomeSlider\Block;

use Magento\Framework\View\Element\Template\Context;
use OM\HomeSlider\Model\HomeSliderFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * HomeSlider View block
 */
class HomeSliderView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var HomeSlider
     */
    protected $_homeslider;
    public function __construct(
        Context $context,
        HomeSliderFactory $homeslider,
        FilterProvider $filterProvider
    ) {
        $this->_homeslider = $homeslider;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('OM HomeSlider Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $homeslider = $this->_homeslider->create();
        $singleData = $homeslider->load($id);
        if($singleData->getHomeSliderId() || $singleData['homeslider_id'] && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}