<?php
/**
 * @category   OM
 * @package    OM_ProductCreate
 * @author     kumar.dhananjay@orangemantra.in
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace OM\ProductCreate\Model\ResourceModel\ProductCreate;
 
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'productcreate_id';
    /**
     * Define model & resource model
     */
    protected function _construct()
    {
        $this->_init(
            'OM\ProductCreate\Model\ProductCreate',
            'OM\ProductCreate\Model\ResourceModel\ProductCreate'
        );
    }
}