<?php




$data 			= $block->getParams();
$invoiceId 		= $data['invoice_id'];
$invoice 		= $block->getInvoice($invoiceId);
$invoiceId 		= $invoice->getIncrementId();
$orderId 		= $invoice->getOrderId();
$order 			= $block->getOrder($orderId); 
$orderId 		= $order->getIncrementId();


$orderDate 		= $block->getTimeAccordingToTimeZone($order->getCreatedAt());

$invoiceDate 	= $block->getTimeAccordingToTimeZone($invoice->getCreatedAt());
$payment 		= $order->getPayment();
$method 		= $payment->getMethodInstance();
$shippingAddress= $block->formatShipping($order);
$billingAddress = $block->formatBilling($order);
$grandTotal 	= $block->formatPrice($invoice->getGrandTotal());
$totalqtys 		= 0;
$shippingAmount = $block->formatPrice($order->getShippingAmount());





$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$order= $objectManager->get('\Magento\Sales\Model\Order');
$orderData=$order->load($orderId);
$state= $orderData->getShippingAddress()->getData("region");// Here is Shipping Address
$orderData->getBillingAddress()->getData();
  

// Here is Billing Address
/* $options = $item->getProductOptions();
var_dump( $options);*/
/*var_dump($order->getData());
exit;*/


ob_end_clean();

//echo $order->getBillingAddress()->getName();
$html = '';

$html .= '<div style="background:#ddd;width:100%;height:100%;"><div style="padding:10px 20px 20px 20px;width:1000px;background:#fff;margin:0 auto;font-size:6pt;line-height:14px;"><table border="0" cellspacing="3" cellpadding="4">';
$html .= '<tr>';
$html .= '<td><h3 style="font-size:7.75pt;line-height:22px;">Tax Invoice :</h3></td>';
$html .= '<td><span>Order Id: <b>'.$orderId.'</b><br>Order Date:'.$orderDate.'</span></td>';
$html .= '<td><span>Invoice No: <b>'.$invoiceId.'</b><br>Invoice Date: '.$invoiceDate.'</span></td>';
$html .= '<td><span>GSTIN: 29AABCC0241R1ZH <br></span></td>';
$html .= '</tr><tr><td colspan="4" style="border-bottom:1px solid #ddd;"><span></span></td></tr>';

$html .= '<tr><td colspan="4">';
$html .= '<table border="0" cellspacing="1" cellpadding="1">';
$html .= '<tr>';
$html .= '<td style="line-height:16px;"><h4>Sold By</h4></td>';
$html .= '<td style="line-height:16px;"><h4>Shipping Address</h4></td>';
$html .= '<td style="line-height:16px;"><h4>Billig Address</h4></td>';
$html .= '</tr>';

$html .= '<tr>';
$html .= '<td style="font-size:5pt;line-height:14px;">Tata Coffee Limited,<br>57 Railway Parallel Road,<br>Kumara Park West,<br>Bengaluru – 560020 Karnataka</td>';
$html .= '<td style="font-size:5pt;line-height:14px;">'.$shippingAddress.'</td>';
$html .= '<td style="font-size:5pt;line-height:14px;">'.$billingAddress.'</td>';
$html .= '</tr>';
$html .= '</table>';



$html .= '</td></tr>';

$html .= '<tr>';
$html .= '<td colspan="4">
 		<table style="border:1px solid #ddd;" cellspacing="0" cellpadding="2">
        <thead>
            <tr class="headings" align="center" valign="center">
                <th class="col-product" style="border-bottom:1px solid #dddddd;" width="120"><span style="line-height:30px;"><b>Product</b></span></th>';
                if($state == "Karnataka"){
                 $html .= '<th class="col-description" style="border-bottom:1px solid #dddddd;" width="120"><span style="line-height:30px;"><b>IGST 5% </b></span></th>';
                
                }else{
                     $html .= '<th class="col-description" style="border-bottom:1px solid #dddddd;" width="60"><span style="line-height:30px;"><b>CGST 2.5% </b></span></th>
                <th class="col-description" style="border-bottom:1px solid #dddddd;" width="60"><span style="line-height:30px;"><b>SGST 2.5% </b></span></th>';
                }

                $html .= '<th class="col-qty" style="border-bottom:1px solid #dddddd;" width="40"><span style="line-height:30px;"><b>Qty</b></span></th>
                <th class="col-gross-amount" style="border-bottom:1px solid #dddddd;" width="80"><span style="line-height:30px;"><b>Amount Inclusive GST</b></span></th>
                <th class="col-discount" style="border-bottom:1px solid #dddddd;" width="70"><span style="line-height:30px;"><b>Discount</b></span></th>
                <th class="col-gst-value" style="border-bottom:1px solid #dddddd;" width="100"><span style="line-height:30px;"><b>Taxable Value</b></span></th>
                
                <th class="col-total last" style="border-bottom:1px solid #dddddd;" width="80"><span style="line-height:30px;"><b>Total</b></span></th>
            </tr>';
$html .= '</thead>';

$_items = $invoice->getAllItems();

$i = 0; 

foreach ($_items as $_item):

if ($_item->getOrderItem()->getParentItem()) { 
continue;
} else { 
  $i++;
} 


$qty = $_item->getQty()*1;
$totalqtys += $qty;
$price 	= '';
$name 	= $_item->getName() . ' | ' .$_item->getSku();
$price 	= $block->formatPrice($_item->getPrice());
$grossAmount = $block->formatPrice($_item->getRowTotalInclTax()); //tax_amount discount_amount total
$gstValue = $block->formatPrice($_item->getRowTotal()); //tax_amount discount_amount total
$taxAmount = $block->formatPrice($_item->getTaxAmount());
$discountAmount = $block->formatPrice($_item->getDiscountAmount());
$total = $block->formatPrice($_item->getRowTotalInclTax()); 
$productId = $_item->getProductId();
$desc =  sprintf("%1\$.2f",$_item->getOrderItem()->getTaxPercent());

$gst = 5;
$rowtotalinclTax = $_item->getRowTotalInclTax();
$gstTaxValue = $block->formatPrice(($rowtotalinclTax*$gst)/100);
//$gstTaxValue1 = round($gstTaxValue/2);


/* items */
$html .='<tr valign="center" align="center" style="line-height:16px;" >';
$html .='<td width="120" class="col-product" style="line-height:16px;">'.$name.'</td>';
if($state == "Karnataka"){
 $html .='<td width="120" class="col-description" style="line-height:16px;">'.$gstTaxValue.'</td>'; 
}else{
$html .='<td width="60" class="col-description" style="line-height:16px;">'.$gstTaxValue.'</td>';
$html .='<td width="60" class="col-description" style="line-height:16px;">'.$gstTaxValue.'</td>';
} 
$html .='<td width="40" class="col-qty" style="line-height:16px;">'.$qty.'</td>';
$html .='<td width="80" class="col-gross-amount" style="line-height:16px;">'.$grossAmount.'</td>';        
$html .='<td width="70" class="col-discount" style="line-height:16px;">'.$discountAmount.'</td>';
$html .='<td width="100" class="col-gst-value" style="line-height:16px;">'.$gstValue.'</td>';

$html .='<td width="80" class="col-total last" style="line-height:16px;">'.$total.'</td>';
$html .='</tr>';




endforeach; 

/* shipping charges */
$html .='<tr valign="center" align="center">';
$html .='<td class="col-product"></td>';
$html .='<td class="col-description"><strong>Shipping Charge</strong></td>';  
$html .='<td class="col-qty">1</td>';
$html .='<td class="col-subtotal">'.$shippingAmount.'</td>';        
$html .='<td class="col-discount">0.00</td>';
$html .='<td class="col-tax">0.00</td>';
$html .='<td class="col-tax">0.00</td>';
$html .='<td class="col-total last">'.$shippingAmount.'</td>';
$html .='</tr>';


/* grand total */
$html .='<tr valign="center" align="center" >';
$html .='<td class="col-product" valign="center" colspan="2" align="left" style="border-top:1px solid #dddddd;line-height:18px;"><strong>TAL QTY: '.$totalqtys.'</strong></td>';
$html .='<td class="col-qty" valign="center" style="border-top:1px solid #dddddd;padding:10px 0;">&nbsp;</td>';
$html .='<td class="col-subtotal" valign="center" style="border-top:1px solid #dddddd;padding:10px 0;">&nbsp;</td>';        
$html .='<td class="col-discount" valign="center" style="border-top:1px solid #dddddd;padding:10px 0;">&nbsp;</td>';
$html .='<td class="col-tax" valign="center" style="border-top:1px solid #dddddd;padding:10px 0;">&nbsp;</td>';
$html .='<td class="col-total last" valign="center" colspan="2" align="right" style="border-top:1px solid #dddddd;line-height:18px;"><strong>TOTAL PRICE:'. $grandTotal.'</strong><br>All values are in INR</td>';
$html .='</tr>';

$html .= '</table></td>';
$html .= '</tr>';

$html .= '<tr>';
$html .= '<td colspan="4">&nbsp;</td>';
$html .= '</tr>';

$html .= '<tr valign="center">';
$html .= '<td colspan="4" style="line-height:12px;font-size:4pt;"><strong>Seller Registered Address: </strong>Tata Coffee Limited,<br>57 Railway Parallel Road,<br>Kumara Park West,<br>Bengaluru – 560020 Karnataka <br> <strong>Declaration</strong> <br>The goods sold are intended for end user consumption and not for resale. </td></tr>';

$html .= '<tr><td colspan="4" align="right">&nbsp;</td></tr>';


$html .= '<tr>';
$html .= '<td colspan="4">&nbsp;</td>';
$html .= '</tr>';


$html .= '<tr>';
$html .= '<td align="left">E. & O.E.</td>';
$html .= '<td>&nbsp;</td>';
$html .= '<td align="left">Ordered Through</td>';
$html .= '<td>&nbsp;</td>';
$html .= '</tr>';

$html .= '<tr>';
$html .= '<td align="left">&nbsp;</td>';
$html .= '<td>&nbsp;</td>';
$html .= '<td>&nbsp;</td>';
$html .= '<td align="right"><strong>Tata Coffee Limited</strong><br />Authorized Signature</td>';
$html .= '</tr>';


$html .= '</table></div></div>';




/*echo $html;
exit;*/
$objectManager = Magento\Framework\App\ObjectManager::getInstance();
$directoryList = $objectManager->get('\Magento\Framework\App\Filesystem\DirectoryList');
$path = $directoryList->getRoot();

define('M2_ROOT',$path.'/');


require_once M2_ROOT ."app/code/OM/Pdf/view/adminhtml/templates/pdf/tcpdf/tcpdf.php";

// Create new PDF
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);



// set document information
//$pdf->SetCreator(PDF_CREATOR);
/*$pdf->SetAuthor('Shiv');
$pdf->SetTitle('Invoice 001');
$pdf->SetSubject('RJ');*/


// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, false, false);


$pdf->SetMargins(8, 17, 8);

$pdf->SetHeaderMargin(2);

    //$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
//$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
//$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
	require_once(dirname(__FILE__).'/lang/eng.php');
	$pdf->setLanguageArray($l);
}

// ---------------------------------------------------------

// set font
$pdf->SetFont('dejavusans', '', 10);

// add a page
$pdf->AddPage();

// Important: this will prevent the generation of the PDF in the browser
// as we are filling the output buffer of PHP

// create some HTML content

// Output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

$pdf->Image('/var/www/html/pub/media/logo/default/sonnets-logo-pdf.png', 8, 0, 30, 12, 'PNG',80);
//$pdf->setSignatureAppearance(10, 0, 20, 15);
//$pdf->addEmptySignatureAppearance(10, 0, 20, 15);
 
$pdf->lastPage();

header('Content-type: application/pdf');
header('Content-Disposition: attachment; filename="invoice_{$invoiceId}.pdf"');

$pdf->Output("invoice_{$invoiceId}.pdf", 'D');

?>