<?php
/**
 * @category   OM
 * @package    OM_Testimonial
 * @author     kumar.dhananjay@orangemantra.in
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace OM\Testimonial\Block;

use Magento\Framework\View\Element\Template\Context;
use OM\Testimonial\Model\TestimonialFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Testimonial View block
 */
class TestimonialView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Testimonial
     */
    protected $_testimonial;
    public function __construct(
        Context $context,
        TestimonialFactory $testimonial,
        FilterProvider $filterProvider
    ) {
        $this->_testimonial = $testimonial;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('OM Testimonial Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $testimonial = $this->_testimonial->create();
        $singleData = $testimonial->load($id);
        if($singleData->getTestimonialId() || $singleData['testimonial_id'] && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}