<?php
/**
 * @category   OM
 * @package    OM_VideoGallery
 * @author     kumar.dhananjay@orangemantra.in
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace OM\VideoGallery\Block;

use Magento\Framework\View\Element\Template\Context;
use OM\VideoGallery\Model\VideoGalleryFactory;
/**
 * VideoGallery List block
 */
class VideoGalleryListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var VideoGallery
     */
    protected $_videogallery;
    public function __construct(
        Context $context,
        VideoGalleryFactory $videogallery
    ) {
        $this->_videogallery = $videogallery;
        parent::__construct($context);
    }

    public function getVideoGalleryCategory()
    {
        $videogallery = $this->_videogallery->create();
        $all_category = $videogallery->getCollection();
        $all_category->addFieldToFilter('status','1');
        $all_category->getSelect()->group('category');
        return $all_category;
    }

   public function getVideoGalleryCollection($category=null){
    if(empty($category)){return null;}
    $videogallery = $this->_videogallery->create();
    $category_wise_data = $videogallery->getCollection();
    if((strtolower($category))=="all")
    {

    }else 
    {
       $category_wise_data = $category_wise_data->addFieldToFilter('category', ['eq'=>$category]);    
 
    }
    return $category_wise_data; 
   }
}  