<?php
/**
 * @category   OM
 * @package    OM_VideoGallery
 * @author     kumar.dhananjay@orangemantra.in
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace OM\VideoGallery\Block;

use Magento\Framework\View\Element\Template\Context;
use OM\VideoGallery\Model\VideoGalleryFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * VideoGallery View block
 */
class VideoGalleryView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var VideoGallery
     */
    protected $_videogallery;
    public function __construct(
        Context $context,
        VideoGalleryFactory $videogallery,
        FilterProvider $filterProvider
    ) {
        $this->_videogallery = $videogallery;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('OM VideoGallery Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $videogallery = $this->_videogallery->create();
        $singleData = $videogallery->load($id);
        if($singleData->getVideoGalleryId() || $singleData['videogallery_id'] && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}